title: All-In-One Website | by Capp
description: Welcome to my Website!
theme: just-the docs
just_the_docs:
  dark_mode: true
  dark_mode_default: true

url: https://RandomTester0.github.io/testing-website
